/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LooksRouteImport } from './routes/looks'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StoryRouteImport } from './routes/story'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as ApiDeskRouteImport } from './routes/api/desk'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as LooksIndexRouteImport } from './routes/looks/index'
import { Route as LooksIdRouteImport } from './routes/looks.$id'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioCopyRouteImport } from './routes/studio/copy'
import { Route as StudioEditRouteImport } from './routes/studio/edit'
import { Route as StudioLiveRouteImport } from './routes/studio/live'
import { Route as StudioOptimizeRouteImport } from './routes/studio/optimize'
import { Route as StudioShopRouteImport } from './routes/studio/shop'
import { Route as StudioSupersRouteImport } from './routes/studio/supers'
import { Route as StudioYoutubeRouteImport } from './routes/studio/youtube'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiYoutubeCallbackRouteImport } from './routes/api/youtube/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LooksRoute = LooksRouteImport.update({
  id: '/looks',
  path: '/looks',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskRoute = ApiDeskRouteImport.update({
  id: '/api/desk',
  path: '/api/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LooksIndexRoute = LooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LooksRoute,
} as any)
const LooksIdRoute = LooksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LooksRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCopyRoute = StudioCopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => StudioRoute,
} as any)
const StudioEditRoute = StudioEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLiveRoute = StudioLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => StudioRoute,
} as any)
const StudioOptimizeRoute = StudioOptimizeRouteImport.update({
  id: '/optimize',
  path: '/optimize',
  getParentRoute: () => StudioRoute,
} as any)
const StudioShopRoute = StudioShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSupersRoute = StudioSupersRouteImport.update({
  id: '/supers',
  path: '/supers',
  getParentRoute: () => StudioRoute,
} as any)
const StudioYoutubeRoute = StudioYoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => StudioRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeCallbackRoute = ApiYoutubeCallbackRouteImport.update({
  id: '/api/youtube/callback',
  path: '/api/youtube/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/looks': typeof LooksRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/story': typeof StoryRoute
  '/studio': typeof StudioRouteWithChildren
  '/support': typeof SupportRoute
  '/watch': typeof WatchRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/orders': typeof ApiOrdersRoute
  '/looks/$id': typeof LooksIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/studio/copy': typeof StudioCopyRoute
  '/studio/edit': typeof StudioEditRoute
  '/studio/live': typeof StudioLiveRoute
  '/studio/optimize': typeof StudioOptimizeRoute
  '/studio/shop': typeof StudioShopRoute
  '/studio/supers': typeof StudioSupersRoute
  '/studio/youtube': typeof StudioYoutubeRoute
  '/looks/': typeof LooksIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/youtube/callback': typeof ApiYoutubeCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/story': typeof StoryRoute
  '/support': typeof SupportRoute
  '/watch': typeof WatchRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/orders': typeof ApiOrdersRoute
  '/looks/$id': typeof LooksIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/studio/copy': typeof StudioCopyRoute
  '/studio/edit': typeof StudioEditRoute
  '/studio/live': typeof StudioLiveRoute
  '/studio/optimize': typeof StudioOptimizeRoute
  '/studio/shop': typeof StudioShopRoute
  '/studio/supers': typeof StudioSupersRoute
  '/studio/youtube': typeof StudioYoutubeRoute
  '/looks': typeof LooksIndexRoute
  '/shop': typeof ShopIndexRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/youtube/callback': typeof ApiYoutubeCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/looks': typeof LooksRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/story': typeof StoryRoute
  '/studio': typeof StudioRouteWithChildren
  '/support': typeof SupportRoute
  '/watch': typeof WatchRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/orders': typeof ApiOrdersRoute
  '/looks/$id': typeof LooksIdRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/studio/copy': typeof StudioCopyRoute
  '/studio/edit': typeof StudioEditRoute
  '/studio/live': typeof StudioLiveRoute
  '/studio/optimize': typeof StudioOptimizeRoute
  '/studio/shop': typeof StudioShopRoute
  '/studio/supers': typeof StudioSupersRoute
  '/studio/youtube': typeof StudioYoutubeRoute
  '/looks/': typeof LooksIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/youtube/callback': typeof ApiYoutubeCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/looks'
    | '/shop'
    | '/story'
    | '/studio'
    | '/support'
    | '/watch'
    | '/api/desk'
    | '/api/orders'
    | '/looks/$id'
    | '/shop/$slug'
    | '/studio/copy'
    | '/studio/edit'
    | '/studio/live'
    | '/studio/optimize'
    | '/studio/shop'
    | '/studio/supers'
    | '/studio/youtube'
    | '/looks/'
    | '/shop/'
    | '/studio/'
    | '/api/auth/$'
    | '/api/youtube/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/story'
    | '/support'
    | '/watch'
    | '/api/desk'
    | '/api/orders'
    | '/looks/$id'
    | '/shop/$slug'
    | '/studio/copy'
    | '/studio/edit'
    | '/studio/live'
    | '/studio/optimize'
    | '/studio/shop'
    | '/studio/supers'
    | '/studio/youtube'
    | '/looks'
    | '/shop'
    | '/studio'
    | '/api/auth/$'
    | '/api/youtube/callback'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/looks'
    | '/shop'
    | '/story'
    | '/studio'
    | '/support'
    | '/watch'
    | '/api/desk'
    | '/api/orders'
    | '/looks/$id'
    | '/shop/$slug'
    | '/studio/copy'
    | '/studio/edit'
    | '/studio/live'
    | '/studio/optimize'
    | '/studio/shop'
    | '/studio/supers'
    | '/studio/youtube'
    | '/looks/'
    | '/shop/'
    | '/studio/'
    | '/api/auth/$'
    | '/api/youtube/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LooksRoute: typeof LooksRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  StoryRoute: typeof StoryRoute
  StudioRoute: typeof StudioRouteWithChildren
  SupportRoute: typeof SupportRoute
  WatchRoute: typeof WatchRoute
  ApiDeskRoute: typeof ApiDeskRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiYoutubeCallbackRoute: typeof ApiYoutubeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/looks': {
      id: '/looks'
      path: '/looks'
      fullPath: '/looks'
      preLoaderRoute: typeof LooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk': {
      id: '/api/desk'
      path: '/api/desk'
      fullPath: '/api/desk'
      preLoaderRoute: typeof ApiDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/looks/': {
      id: '/looks/'
      path: '/'
      fullPath: '/looks/'
      preLoaderRoute: typeof LooksIndexRouteImport
      parentRoute: typeof LooksRoute
    }
    '/looks/$id': {
      id: '/looks/$id'
      path: '/$id'
      fullPath: '/looks/$id'
      preLoaderRoute: typeof LooksIdRouteImport
      parentRoute: typeof LooksRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/copy': {
      id: '/studio/copy'
      path: '/copy'
      fullPath: '/studio/copy'
      preLoaderRoute: typeof StudioCopyRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/edit': {
      id: '/studio/edit'
      path: '/edit'
      fullPath: '/studio/edit'
      preLoaderRoute: typeof StudioEditRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/live': {
      id: '/studio/live'
      path: '/live'
      fullPath: '/studio/live'
      preLoaderRoute: typeof StudioLiveRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/optimize': {
      id: '/studio/optimize'
      path: '/optimize'
      fullPath: '/studio/optimize'
      preLoaderRoute: typeof StudioOptimizeRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/shop': {
      id: '/studio/shop'
      path: '/shop'
      fullPath: '/studio/shop'
      preLoaderRoute: typeof StudioShopRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/supers': {
      id: '/studio/supers'
      path: '/supers'
      fullPath: '/studio/supers'
      preLoaderRoute: typeof StudioSupersRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/youtube': {
      id: '/studio/youtube'
      path: '/youtube'
      fullPath: '/studio/youtube'
      preLoaderRoute: typeof StudioYoutubeRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/callback': {
      id: '/api/youtube/callback'
      path: '/api/youtube/callback'
      fullPath: '/api/youtube/callback'
      preLoaderRoute: typeof ApiYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LooksRouteChildren {
  LooksIdRoute: typeof LooksIdRoute
  LooksIndexRoute: typeof LooksIndexRoute
}

const LooksRouteChildren: LooksRouteChildren = {
  LooksIdRoute: LooksIdRoute,
  LooksIndexRoute: LooksIndexRoute,
}

const LooksRouteWithChildren = LooksRoute._addFileChildren(LooksRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface StudioRouteChildren {
  StudioCopyRoute: typeof StudioCopyRoute
  StudioEditRoute: typeof StudioEditRoute
  StudioLiveRoute: typeof StudioLiveRoute
  StudioOptimizeRoute: typeof StudioOptimizeRoute
  StudioShopRoute: typeof StudioShopRoute
  StudioSupersRoute: typeof StudioSupersRoute
  StudioYoutubeRoute: typeof StudioYoutubeRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioCopyRoute: StudioCopyRoute,
  StudioEditRoute: StudioEditRoute,
  StudioLiveRoute: StudioLiveRoute,
  StudioOptimizeRoute: StudioOptimizeRoute,
  StudioShopRoute: StudioShopRoute,
  StudioSupersRoute: StudioSupersRoute,
  StudioYoutubeRoute: StudioYoutubeRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LooksRoute: LooksRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  StoryRoute: StoryRoute,
  StudioRoute: StudioRouteWithChildren,
  SupportRoute: SupportRoute,
  WatchRoute: WatchRoute,
  ApiDeskRoute: ApiDeskRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiYoutubeCallbackRoute: ApiYoutubeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
